# `numpy

- one of the core packages for numerical computing in Python
- many packages are built on top of numpy
-`numpy` has been been optimized for processing: faster than due to memory access

In [3]:
# import Numpy with standard abbreviation

import numpy as np

# Variables

We can think about variables as a bane we assign to a particular object in Python.

In [4]:
# assign a small array to a variable a 
a = np.array( [ [1,1,2], [3,5,8] ] )


When we run a cell we store the variable and its value. We can see the variable's value in two ways:

In [5]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [6]:
print(a)

[[1 1 2]
 [3 5 8]]


## Naming variables

In the class we are going to use `snake_case` for naming variables.

# Variables and objects

**object**: often encountered in Python documentation and tutorials.
Object is a bundle of properties and actions about something specific.
Example:

- object: dataframe
    - properties: number of rows, names of columns, data created
    - actions: selecting a row, adding a column
    
A variable is a name we give a specific object, and the same object can be referenced by different variables.

Example:
- The Sun (actual star at the center of solar system) = object
- sol = Spanish word fo Sun = variable
- soleil = Fren for Sun = another variable

In practice: we will use object and variable interchanngeably 


# Types 

Each obejct in Python has a type.

type = what kind of object it is

We can also call the type of the object, the **class** of the object.

We can see the type / class of an object by using `type` function:

In [7]:
print(a)
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

The `numpy.ndarray` is the core onject/datatype in the NumPy package. We can check the type of an e
ntry in the array by indexing:

In [8]:
print(a[0,0])
type(a[0,0])

1


numpy.int64

In [ ]:
# How would you access the value 5 in the array a ?

In [10]:
print(a)
(a[1,1])

[[1 1 2]
 [3 5 8]]


5

# Functions

`print` was our first example of a Python function!

A function:
- take in a set of **arguments**, separated by commas, and 
- use those arguments to produce some **output**

argument = parameter : you might see argument more frequently in the documentation

Use `?` followed by the function name to get information about a function

In [11]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


- first line: function showing all of its argnuments in parenthesis
- then a short description of what the function does
- finally, a list of the arguments and a brief explanation of each of them.

Different types of arguments inside the paranthesis. 
Two base types:
- **non-optional arguments**: arguments you need to specify for the function to do something
- **optional arguments**: arguments are pre-filled with a default value by the function bu t we can pverride them. Optional arguments appear inside the paranthesis in the form:
`optional argument = default_value`

In [12]:
print('changing the default end argument of the print function', end = ':)') 

changing the default end argument of the print function:)

# Attributes and Methods

An object in Python has attribute and methods.

- **attributes**: a propperty of an object , a piece of information about it.
- **methods**: a procedure associated with an object. = a function() where the main parameter us the object.

Access a variable's attributes and methods by adding a period `.` at the end of the variable's name.

`variable.variable_method()` or
`variable.variable_attribute`

Examples:

Methods and attributes of NumPy arrays:

In [1]:
import numpy as np

In [2]:
# define a 3x3 array

var = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
var

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# attributes
# shape : attribute telling the number of elements in each dimension of the array

var.shape

(3, 3)

In [4]:
type(var.shape)

tuple

In [5]:
# ndim: attribute that holds the number of array dimensions
var.ndim

2

In [6]:
type(var.ndim)

int

- Notice attributes can have many different data types.

Examples of methods

In [7]:
# min method for array: returns a minimum value in the array
var.min()

1

In [8]:
type(var.min)

builtin_function_or_method

# R and Python

R:
- does not use methods within an object
- functions in R are extrinsic to (outside) the objects thay are acting on 

Example: recreate getting the mean value in an arrray

In R there would be two separate items: the variable `var` and a **separate** function `min` that gets `var` as a parameter:

```
# this is R code
var <- array(c(1,4,7,2,5,8,3,6,9), dim=c(3,3))
min(var)
```

Using the pipe operator >%> in R's tidyverse is closer to the `.` in Python

```
var <- array(c(1,4,7,2,5,8,3,6,9), dim=c(3,3))
var >%> min()
```

The pipe is passing `var` to the `min()` as its first argument. This is similar to the `.` in Python.

```
var = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
var.min()
```

